### ISSUE TITLE
微件展示不全

### ISSUE THREAD

**Issue by jqtmviyu** [zkywalker/GenshinWidgets#10]
| 问题描述 | 微件展示不全 |
| -------- | ------------ |
| 软件版本 | 0.1.1        |
| 设备型号 | k30s         |
| 系统版本 | miui12.0.12  |
| 分辨率   | 2400*1080    |
| 屏幕尺寸 | 6.67英寸     |
| 布局设置 | 5*6          |  

![image](https://user-images.githubusercontent.com/19925192/185326303-32a2feb0-fd1e-421b-8d7e-f34d6acd9d84.png)

**Comment by zkywalker** [comment]
麻烦试下新版本：https://github.com/zkywalker/GenshinWidgets/releases/tag/v0.1.2
预期是这样的
![Screenshot_2022_0819_154601](https://user-images.githubusercontent.com/11813277/185580650-dbe6264e-bbf1-490c-95d4-9b15b89319ea.jpg)
