### ISSUE TITLE
有个小小的问题想让你解答下

### ISSUE THREAD

**Issue by Yue-cn** [zkywalker/GenshinWidgets#12]
找不到你的联系方式是真的很麻烦:(
每次请求这个character必定-10001
![image](https://user-images.githubusercontent.com/79188080/189662576-50ee9752-8114-4a73-a944-28d325ce40f9.png)
![image](https://user-images.githubusercontent.com/79188080/189662906-57684f71-795a-4700-9038-8fadf59fc7eb.png)

**Comment by zkywalker** [comment]
请求自己卡池那个接口吗，我记得我扒米游社的时候拼参数也是拼了半天
安卓项目会跑吗，跑下我项目打印参数对比下
